import math
print('Oh hey, you need to do some math but are too lazy to do it yourself?')
print('Well you came to the right place!')
mass = float(input('What is the mass of the object? Please enter the value in kg: '))
gravity = float(input('What is the graviy of the planet? Please enter the value in m/s^2, 9.8 for Earth and 24 for Jupiter: '))
time = float(input('How long did the object fall in seconds? Please enter the value in seconds: '))
density = float(input('What is the density off the fluid? Please enter the vaule in kg/m^3, 1.3 for air, 1000 for water: '))
cross_section = float(input('What is the cross sectional area? Please enter value in m^2: '))
drag_const = float(input('What is the drag constant? 0.5 for sphere, 1.1 for cylinder: '))
inner_c = (1/2) * density * cross_section * drag_const
str(inner_c)
print(f'The inner value of c is: {inner_c:.3f}')
velocity = (math.sqrt((mass * gravity) / inner_c)) * (1 - math.exp((-math.sqrt(mass * gravity * inner_c) / mass) * time))
str(velocity)
print(f'The velocity of the object is: {velocity:.3f}')
