print('Please gib meh all yer info')
print('')
first_name = input('Your first name: ')
print('Ooo, pretty')
last_name = input('And your last name: ')
email = input('What is your email: ')
number = input('Hey baby, what is your number? ')
hair = input('Your hair color is? ')
eyes = input('Your eye color is? ')
print('Hey, I just work here.')
job = input('What is your job title, exactly? ')
month = input('Oh yeah, what month did you start here? ')
training = input('And did you complete the advanced training? Just put yes or no ')
ID = input('And finally, your ID number: ')
print('')
print('Thank you, ' + first_name.capitalize())
print('Here is your ID Badge')
print('-----------------------------')
print('')
print(last_name.upper() + ', ' + first_name.capitalize())
print(job.title())
print('ID: ' + ID)
print('')
print(email.lower())
print(number)
print('')
print(f'Hair: {hair.capitalize():15} Eyes: {eyes.capitalize():14}')
print(f'Month: {month.capitalize():14} Training: {training.capitalize()}')
print('-----------------------------')