name = input('Oh hey! What is your name? ').capitalize()
print(f'Wanna hear a story, {name}? It is a fun one, it requires your help!')
adjective_one = input('Choose an adjective, if you would be so kind: ')
animal_one = input('What is your favorite animal? ')
verb_one = input('Now choose a verb: ')
exclamation_one = input('Quick! Choose an excalmaition! ').capitalize()
exclamation_two = input('Now take your time and choose another exclamation: ').capitalize()
verb_two = input('Choose another verb please, and try to make this one more creative: ')
verb_three = input('Alright, you get one more try at a fun verb: ')
animal_two = input('Okay, now choose another animal, any animal at all: ')
place = input('Pick a place, any place! ')
food = input('Hey, what is your favorite food? ')
adjective_two = input('Good choice, now pick an adjective: ')
noun_p = input('And finally, choose a plural noun! ')

print(f'Alright! {name} Story time!')
print(f'The other day, I was really in trouble. It all started when I saw a very {adjective_one} {animal_one} {verb_one} down the hallway. "{exclamation_one}!" I yelled. And then the {animal_one} yelled back! "{exclamation_two}!" But all I could think to do was to {verb_two} over and over. Miraculously, that caused it to stop, but not before it tried to {verb_three} right in front of my family, who were all riding a {animal_two} all over {place}. So I guess {food} are best eaten without {adjective_two} {noun_p}.')